apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptt-frontend
  template:
    metadata:
      labels:
        app: ptt-frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
