/**
 * ptt-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RequestContentType} from './requestContentType';
import {HttpStepHeaderDto} from './httpStepHeaderDto';


export interface HttpStepDto {
    id?: number;
    name?: string;
    description?: string;
    method?: string;
    url?: string;
    body?: string;
    responseContentType?: RequestContentType;
    contentType?: RequestContentType;
    headers?: Array<HttpStepHeaderDto>;
}

