/**
 * ptt-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OutputType = 'PLAIN_TEXT' | 'OCTET_STREAM' | 'FROM_INPUT_PARAMETER';

export const OutputType = {
    PlainText: 'PLAIN_TEXT' as OutputType,
    OctetStream: 'OCTET_STREAM' as OutputType,
    FromInputParameter: 'FROM_INPUT_PARAMETER' as OutputType
};

