export * from './dataPointAggregationResource.service';
import {DataPointAggregationResourceService} from './dataPointAggregationResource.service';
import {DataPointResourceService} from './dataPointResource.service';
import {HttpStepResourceService} from './httpStepResource.service';
import {InputArgumentResourceService} from './inputArgumentResource.service';
import {NodeResourceService} from './nodeResource.service';
import {OutputArgumentResourceService} from './outputArgumentResource.service';
import {PlanResourceService} from './planResource.service';
import {PlanRunResourceService} from './planRunResource.service';
import {ScriptStepResourceService} from './scriptStepResource.service';
import {StepParameterRelationResourceService} from './stepParameterRelationResource.service';
import {StepResourceService} from './stepResource.service';

export * from './dataPointResource.service';
export * from './httpStepResource.service';
export * from './inputArgumentResource.service';
export * from './nodeResource.service';
export * from './outputArgumentResource.service';
export * from './planResource.service';
export * from './planRunResource.service';
export * from './scriptStepResource.service';
export * from './stepParameterRelationResource.service';
export * from './stepResource.service';
export const APIS = [DataPointAggregationResourceService, DataPointResourceService, HttpStepResourceService, InputArgumentResourceService, NodeResourceService, OutputArgumentResourceService, PlanResourceService, PlanRunResourceService, ScriptStepResourceService, StepParameterRelationResourceService, StepResourceService];
